# Generated by Django 3.0.3 on 2021-07-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='file',
            field=models.ManyToManyField(blank=True, related_name='files', to='main.File'),
        ),
    ]
