# Generated by Django 3.0.3 on 2021-07-19 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210719_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Folder', unique=True)),
            ],
        ),
    ]
